# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
 - 5.6
 - 7.0
 - 7.1
 - 7.2
 - 7.3
 
 #RabbitMQ uses the default configuration:
#vhost: /
#username: guest
#password: guest
#You can set up more vhosts and roles in the before_script section of your .travis.yml.
services:
 - rabbitmq
 
install:
 - composer install --no-interaction
  # enabled rabbitmq_management plugin to check queue
 - sudo rabbitmq-plugins enable rabbitmq_management
 - sudo wget http://guest:guest@localhost:15672/cli/rabbitmqadmin -O /usr/local/bin/rabbitmqadmin
 - sudo chmod +x /usr/local/bin/rabbitmqadmin
 # setup exchange, queue & binding
 - rabbitmqadmin declare exchange name=indexing type=direct
 - rabbitmqadmin declare queue name=indexing durable=true
 - rabbitmqadmin declare binding source=indexing destination=indexing
 # define a test user (because rabbit will be accessed from the Docker image, guest/guest won't work)
 - sudo rabbitmqctl add_user test test
 - sudo rabbitmqctl set_user_tags test administrator
 - sudo rabbitmqctl set_permissions -p / test ".*" ".*" ".*" 
 
notifications:
  email: false
